### ISSUE TITLE
1.4.1无法有效添加自定义地址

### ISSUE THREAD

**Issue by Yuyoo** [casuallyName/Geocoding#3]
respect～使用过程中遇到一些问题，无法有效添加自定义地址。

自定义示例代码如下：
```
geocoding = Geocoding()
geocoding.addRegionEntry(1, 321200000000, "A街道", geocoding.RegionType.Street)
print(geocoding.normalizing("江苏泰州A街道"))

```
返回的结果：
```
Address(
	provinceId=320000000000, province=江苏省, 
	cityId=321200000000, city=泰州市, 
	districtId=None, district=None, 
	streetId=None, street=None, 
	townId=None, town=None, 
	villageId=None, village=None, 
	road=None, 
	roadNum=None, 
	buildingNum=None, 
	text=A街道
)
```

并不能将A街道添加到street参数里。

另外，批量导入自定义地址文件应该放在哪？地址文件的格式是啥？

**Comment by DarkPet** [comment]
批量导入地址文件放哪里都行：geo = Geocoding(data_class_path = "D:\\PythonProjects\\Address\\region.dat");

**Comment by fjklqq** [comment]
1. 对于自定义地址的问题，可以参看 #4 ，目前可以先试用上一个版本临时解决一下。
2. 对于自定义地址文件的格式问题，可参考原项目的[说明](https://github.com/bitlap/geocoding#2-%E8%AF%B4%E6%98%8E)
