### ISSUE TITLE
添加自定义地址失败

### ISSUE THREAD

**Issue by DarkPet** [casuallyName/Geocoding#4]
添加自定义地址失败，geocoding.addRegionEntry(1, 321200000000, "A街道", geocoding.RegionType.Street) 总是返回 False
无法得到想要的结果
Address(
        provinceId=320000000000, province=江苏省,
        cityId=321200000000, city=泰州市,
        districtId=None, district=None,
        streetId=None, street=None,
        townId=None, town=None,
        villageId=None, village=None,
        road=None,
        roadNum=None,
        buildingNum=None,
        text=A街道
)

**Comment by fjklqq** [comment]
是的，昨天Debug了一下，发现在JVM执行`GeocodingX.addRegionEntry`方法时，会出现找不到匹配的重载的问题。

```
TypeError: No matching overloads found for org.bitlap.geocoding.GeocodingX.addRegionEntry(), options are:
	public final org.bitlap.geocoding.GeocodingX org.bitlap.geocoding.GeocodingX.addRegionEntry(long,long,java.lang.String,org.bitlap.geocoding.model.RegionType,java.lang.String,boolean)
```

看了一下项目源码，参数类型应该是匹配的，所以还没有解决方案（主要是Java代码的能力我仅限于读一读了解个大概）

后面再看一下具体是什么原因导致的。

**目前可以先安装上一个版本来使用自定义地址功能**

**Comment by DarkPet** [comment]
我可能知道问题出在哪里
`
    /**
     * 设置自定义地址
     *
     * @param id          地址的ID
     * @param parentId    地址的父ID, 必须存在
     * @param name        地址的名称
     * @param type        地址类型, [RegionType]
     * @param alias       地址的别名
     * @param replace     是否替换旧地址, 当除了[id]之外的字段, 如果相等就替换
     */
    fun addRegionEntry(id: Long, parentId: Long, name: String, type: RegionType = RegionType.Undefined, alias: String = "", replace: Boolean = true): GeocodingX {
        ctx.persister.getRegion(parentId) ?: throw IllegalArgumentException("Parent Address is not exists, parentId is $parentId")
        if (name.isBlank()) {
            throw IllegalArgumentException("name should not be blank.")
        }
        // 构建 region 对象
        val region = RegionEntity()
        region.id = id
        region.parentId = parentId
        region.name = name
        region.alias = alias
        region.type = type
        // 1. Add to cache (id -> Region)
        ctx.persister.addRegionEntity(region)
        // 2. Build term index
        val indexBuilder = ctx.interpreter.getTermIndexBuilder()
        indexBuilder.indexRegions(listOf(region), replace)
        return this
    }`
估计是需要把JAVA代码中的返回值去掉才能识别

**Comment by DarkPet** [comment]
找到问题了
        try:
            self.geocoding.addRegionEntry(id=Id, parentId=parentId, name=name,
                                          RegionType=RegionType, alias=alias, replace=replace)
            return True
        except:
            return False
修改为:
        try:
            self.geocoding.addRegionEntry(Id, parentId, name, RegionType, alias, replace)
            return True
        except:
            return False

**Comment by fjklqq** [comment]
> 找到问题了
> 
>         try:
> 
>             self.geocoding.addRegionEntry(id=Id, parentId=parentId, name=name,
> 
>                                           RegionType=RegionType, alias=alias, replace=replace)
> 
>             return True
> 
>         except:
> 
>             return False
> 
> 修改为:
> 
>         try:
> 
>             self.geocoding.addRegionEntry(Id, parentId, name, RegionType, alias, replace)
> 
>             return True
> 
>         except:
> 
>             return False

好的，今晚测试一下，顺便更新一下jar包。

**Comment by DarkPet** [comment]
@casuallyName
