### ISSUE TITLE
分词方法segment解析【郫都区】问题

### ISSUE THREAD

**Issue by warrior156006050** [casuallyName/Geocoding#6]
输入：四川省成都市郫都区西源大道1311号3栋4单元1楼102号
segment方法，seg_type = 'ik',
分词结果list为：['四川省', '成都市', '郫', '都', '西源大道', '1311号', '3栋', '4', '单元', '1楼', '102号']
期望结果list为：['四川省', '成都市', '郫都区',  '西源大道', '1311号', '3栋', '4', '单元', '1楼', '102号']
请问有啥办法修正结果吗？感谢！

输入：四川省成都市双流区西航港街道临港路四段9号和贵久居福4栋3单元4层402号
分词结果list为：['四川省', '成都市', '双流', '西航港街道', '临港路', '四段', '9号', '和贵久居福', '4栋', '3', '单元', '4层', '402号']
双流区的区字被分词没了？是啥原因

**Comment by fjklqq** [comment]
这个问题就需要在源项目下提交Issue解决了
