### ISSUE TITLE
1.4.3新方法的用例

### ISSUE THREAD

**Issue by warrior156006050** [casuallyName/Geocoding#7]
请问可以增加一些1.4.3版本新方法（save、match、analyze）的使用说明和例子吗？感谢

**Comment by fjklqq** [comment]
* `save`方法可以在使用`addRegionEntry`方法进行自定义地址设置后进行保存，并在下次初始化时加载，避免重复复进行构建自定义地址操作。
* 这个三个方法都是[源项目作者](https://github.com/bitlap/geocoding)在最近几次commit中新增的方法，源项目也没有做过多介绍，具体可以参考源项目的[analyze方法](https://github.com/bitlap/geocoding/blob/1947d075bce44450a5fb6ae55c3ee282a11c4de2/src/main/java/org/bitlap/geocoding/GeocodingX.kt#L38)、[match方法](https://github.com/bitlap/geocoding/blob/1947d075bce44450a5fb6ae55c3ee282a11c4de2/src/main/java/org/bitlap/geocoding/GeocodingX.kt#L78)、[save方法](https://github.com/bitlap/geocoding/blob/1947d075bce44450a5fb6ae55c3ee282a11c4de2/src/main/java/org/bitlap/geocoding/GeocodingX.kt#L115)。
